"""Create/refresh the "BWH Newsletter" Jinja Print Format for Newsletter Issue.

The template is fully theme-driven: every colour, font, spacing and layout
decision is read from the Newsletter Style linked on the Issue (with sane
defaults when a field is blank), so switching Issue.style swaps the whole
look. Sections marked "Highlight as Panel" render as a coloured panel with
card-style topics using the theme's panel/card colours.

Run with: bench --site dev.localhost execute newsletter.setup_print_format.create_print_format

Rendering constraints baked in (learned the hard way on this bench):
- wkhtmltopdf (the "Get PDF" button) has no network access, so nothing here
  may reference an external URL. Fonts are served from this app's own
  /assets/newsletter/fonts/ and declared with local() first, so the server
  uses its installed copies and the browser downloads them once.
- wkhtmltopdf's flexbox is unreliable (rows collapse); side-by-side rows use
  inline-block + vertical-align.
- No color-mix()/var(): tints are computed with the hex_to_rgba() helper.
"""

import frappe

PRINT_FORMAT_NAME = "BWH Newsletter"

# family -> list of (file, weight, style); all open-licensed and copied into
# newsletter/public/fonts/ so the browser can fetch them.
BUNDLED_FONTS = {
	"Limelight": [("Limelight.ttf", 400, "normal")],
	"Lobster": [("Lobster.ttf", 400, "normal")],
	"Raleway": [
		("Raleway-ExtraLight.ttf", 200, "normal"),
		("Raleway-Light.ttf", 300, "normal"),
		("Raleway-Regular.ttf", 400, "normal"),
		("Raleway-Medium.ttf", 500, "normal"),
		("Raleway-SemiBold.ttf", 600, "normal"),
		("Raleway-Bold.ttf", 700, "normal"),
		("Raleway-ExtraBold.ttf", 800, "normal"),
	],
	"Open Sans": [
		("OpenSans-Light.ttf", 300, "normal"),
		("OpenSans-Regular.ttf", 400, "normal"),
		("OpenSans-Italic.ttf", 400, "italic"),
		("OpenSans-Semibold.ttf", 600, "normal"),
		("OpenSans-Bold.ttf", 700, "normal"),
	],
	"Noto Sans": [
		("NotoSans-Regular.ttf", 400, "normal"),
		("NotoSans-Italic.ttf", 400, "italic"),
		("NotoSans-Bold.ttf", 700, "normal"),
	],
	"Noto Serif": [
		("NotoSerif-Regular.ttf", 400, "normal"),
		("NotoSerif-Italic.ttf", 400, "italic"),
		("NotoSerif-Bold.ttf", 700, "normal"),
		("NotoSerif-BoldItalic.ttf", 700, "italic"),
	],
	"DejaVu Sans Mono": [
		("DejaVuSansMono.ttf", 400, "normal"),
		("DejaVuSansMono-Bold.ttf", 700, "normal"),
	],
	"Droid Serif": [
		("DroidSerif-Regular.ttf", 400, "normal"),
		("DroidSerif-Italic.ttf", 400, "italic"),
		("DroidSerif-Bold.ttf", 700, "normal"),
	],
	"Liberation Sans": [
		("LiberationSans-Regular.ttf", 400, "normal"),
		("LiberationSans-Bold.ttf", 700, "normal"),
	],
}


FONTS_CSS_PATH = frappe.get_app_path("newsletter", "public", "css", "fonts.css")


def _write_fonts_css():
	"""Write public/css/fonts.css with one @font-face per bundled face.

	The rules live in a separate stylesheet rather than inline in the print
	format on purpose: Frappe's PDF pipeline only absolutises `url()` when it
	directly follows a colon, so an inline `src: local(..), url(..)` stays
	relative and wkhtmltopdf fails with ProtocolUnknownError. A <link href>
	IS absolutised for the PDF (and stays relative for the browser), and the
	font url()s inside the file resolve relative to the stylesheet itself in
	both renderers.
	"""
	import os

	rules = ["/* Generated by newsletter.setup_print_format - do not edit by hand. */"]
	for family, faces in BUNDLED_FONTS.items():
		for filename, weight, style in faces:
			rules.append(
				"@font-face { font-family: '%s'; font-weight: %d; font-style: %s; "
				"src: local('%s'), url('../fonts/%s') format('truetype'); }"
				% (family, weight, style, family, filename)
			)
	os.makedirs(os.path.dirname(FONTS_CSS_PATH), exist_ok=True)
	with open(FONTS_CSS_PATH, "w") as f:
		f.write("\n".join(rules) + "\n")


HTML = r"""
{%- set S = frappe.get_doc("Newsletter Style", doc.style) if doc.style else None -%}

{#- ---------- Theme variables, every one with a fallback ---------- -#}
{%- set page_bg   = (S.background_color if S and S.background_color else '#ffffff') -%}
{%- set page_fg   = (S.text_color if S and S.text_color else '#1c1c22') -%}
{%- set accent    = (S.accent_color if S and S.accent_color else (S.border_color if S and S.border_color else '#4f46e5')) -%}
{%- set muted     = (S.muted_text_color if S and S.muted_text_color else '#8a8a92') -%}
{%- set divider   = (S.divider_color if S and S.divider_color else hex_to_rgba(page_fg, 0.12)) -%}
{%- set panel_bg  = (S.panel_background_color if S and S.panel_background_color else '') -%}
{%- set card_bg   = (S.card_background_color if S and S.card_background_color else page_bg) -%}
{%- set palette   = ((S.section_accent_palette or '') if S else '').split(',') | map('trim') | reject('equalto', '') | list -%}

{%- set font_display = (S.display_font if S and S.display_font else "'Limelight', Georgia, 'Times New Roman', serif") -%}
{%- set font_heading = (S.heading_font if S and S.heading_font else "'Raleway', 'Century Gothic', 'Trebuchet MS', sans-serif") -%}
{%- set font_label   = (S.label_font if S and S.label_font else font_heading) -%}
{%- set font_body    = (S.font_family if S and S.font_family else "'Open Sans', 'Segoe UI', Helvetica, Arial, sans-serif") -%}
{%- set heading_upper = (S and S.heading_style == 'Uppercase') -%}
{%- set body_size = (S.body_font_size if S and S.body_font_size else 14) -%}
{%- set lh        = (S.line_height if S and S.line_height else 1.75) -%}
{%- set para      = (S.paragraph_spacing if S and S.paragraph_spacing else 12) -%}

{%- set masthead_left = (S and S.masthead_alignment == 'Left') -%}
{%- set show_numbers  = (S.show_section_numbers if S else 1) -%}
{%- set accent_headings = (S.accent_headings if S else 0) -%}
{%- set divider_style = (S.divider_style if S and S.divider_style else 'Hairline') -%}
{%- set radius = (S.corner_radius if S else 14) -%}
{%- set card_border = ((S.border_width|string) ~ 'px ' ~ (S.border_style|lower) ~ ' ' ~ (S.border_color or accent)) if S and S.border_style and S.border_style != 'None' and S.border_width else 'none' -%}
{%- set gutter = '34px' -%}

<link rel="stylesheet" href="/assets/newsletter/css/fonts.css">

<div class="bwh-newsletter" style="font-family: {{ font_body }}; background-color: {{ page_bg }}; color: {{ page_fg }}; position: relative;">

<style>
  .bwh-newsletter { font-size: {{ body_size }}px; line-height: {{ lh }}; -webkit-font-smoothing: antialiased; }
  /* Frappe's print bundle has a Bootstrap print reset: @media print { * { color: #000; background: transparent } }.
     A direct rule beats an inherited value, so every plain p/div/span would print black on dark themes.
     (0,1,0) specificity here outranks that (0,0,0) rule and restores normal inheritance; explicit class
     rules and inline colours still win as usual. */
  .bwh-newsletter * { box-sizing: border-box; color: inherit; }
  .bwh-newsletter img { max-width: 100%; }

  /* One shared horizontal gutter so every block's text sits on the same left edge. */
  .bwh-masthead, .bwh-intro, .bwh-toc, .bwh-section, .bwh-footer { padding-left: {{ gutter }}; padding-right: {{ gutter }}; }

  .bwh-banner { width: 100%; max-height: 150px; object-fit: cover; display: block; }

  /* ---- Masthead ---- */
  .bwh-masthead { text-align: {{ 'left' if masthead_left else 'center' }}; padding-top: 44px; padding-bottom: 26px; }
  .bwh-wordmark { display: inline-block; font-family: {{ font_label }}; font-weight: 700; font-size: 13px; letter-spacing: 0.35em; text-transform: uppercase; color: {{ accent }}; }
  .bwh-masthead h1 { font-family: {{ font_display }}; font-size: 34px; font-weight: 400; line-height: 1.2; margin: 18px 0 12px 0; color: {{ page_fg }}; }
  .bwh-masthead .bwh-meta { font-family: {{ font_label }}; color: {{ muted }}; font-size: 11.5px; letter-spacing: 0.08em; text-transform: uppercase; }
  .bwh-cover-img { max-width: 100%; max-height: 240px; border-radius: {{ radius }}px; margin: 24px {{ '0' if masthead_left else 'auto' }} 4px {{ '0' if masthead_left else 'auto' }}; display: block; }
  .bwh-rule { width: 60px; height: 2px; background: {{ accent }}; margin: 24px {{ '0' if masthead_left else 'auto' }} 0 {{ '0' if masthead_left else 'auto' }}; border: none; }

  .bwh-intro { padding-top: 6px; padding-bottom: 30px; font-family: {{ font_heading }}; font-style: italic; font-size: {{ body_size + 2 }}px; line-height: {{ lh + 0.1 }}; color: {{ hex_to_rgba(page_fg, 0.85) }}; text-align: {{ 'left' if masthead_left else 'center' }}; }
  .bwh-newsletter .bwh-intro p { margin: 0 0 {{ para }}px 0; }
  .bwh-newsletter .bwh-intro p:last-child { margin-bottom: 0; }

  /* ---- Contents ---- */
  .bwh-toc { padding-bottom: 32px; font-family: {{ font_label }}; font-size: 11px; letter-spacing: 0.06em; text-transform: uppercase; line-height: 2.2; text-align: {{ 'left' if masthead_left else 'center' }}; }
  .bwh-toc a { color: {{ muted }}; text-decoration: none; }
  .bwh-toc a:not(:last-child)::after { content: "\2022"; margin: 0 10px; color: {{ accent }}; }

  /* ---- Sections ---- */
  .bwh-section { padding-top: 30px; padding-bottom: 30px; page-break-inside: avoid; }
  .bwh-section-panel { margin: 24px 0; border-radius: {{ radius }}px; padding-top: 32px; padding-bottom: 32px; }

  /* The title itself is display:inline (wkhtmltopdf wraps inline-block headings at their minimum
     width); the index and dot are inline-blocks vertically centred on the title's line box. */
  .bwh-eyebrow { margin-bottom: 22px; line-height: 1.3; }
  .bwh-eyebrow .bwh-index, .bwh-eyebrow .bwh-dot { display: inline-block; vertical-align: middle; }
  .bwh-eyebrow .bwh-index { font-family: {{ font_label }}; font-size: 13px; color: {{ muted }}; letter-spacing: 0.05em; margin-right: 12px; line-height: 1; }
  .bwh-eyebrow .bwh-dot { width: 7px; height: 7px; border-radius: 50%; margin-right: 12px; }
  .bwh-section-title { display: inline; font-family: {{ font_heading }}; font-size: 22px; font-weight: 700; margin: 0; line-height: 1.3; vertical-align: middle; {% if heading_upper %}text-transform: uppercase; letter-spacing: 0.06em;{% endif %} }

  /* ---- Topics: single column ---- */
  .bwh-topics-list { display: block; }
  .bwh-section-plain .bwh-topic { width: 100%; padding: 22px 0; border-bottom: 1px solid {{ divider }}; }
  .bwh-section-plain .bwh-topic:first-child { padding-top: 0; }
  .bwh-section-plain .bwh-topic:last-child { border-bottom: none; padding-bottom: 4px; }

  .bwh-section-panel .bwh-topic { width: 100%; background: {{ card_bg }}; border: {{ card_border }}; border-radius: {{ radius }}px; padding: 22px 24px; }
  .bwh-section-panel .bwh-topic:not(:last-child) { margin-bottom: 16px; }

  .bwh-topic-title { font-family: {{ font_heading }}; font-size: {{ body_size + 4 }}px; font-weight: 700; line-height: 1.3; margin: 0 0 12px 0; }

  /* ---- Contents: several pieces under one topic ---- */
  .bwh-content + .bwh-content { margin-top: 18px; padding-top: 18px; border-top: 1px dashed {{ divider }}; }
  .bwh-content-title { font-family: {{ font_heading }}; font-size: {{ body_size + 1 }}px; font-weight: 600; line-height: 1.35; margin: 0 0 10px 0; }

  .bwh-topic-content { font-size: {{ body_size }}px; line-height: {{ lh }}; margin-bottom: 14px; }
  .bwh-newsletter .bwh-topic-content p { margin: 0 0 {{ para }}px 0; }
  .bwh-newsletter .bwh-topic-content p:last-child { margin-bottom: 0; }
  .bwh-newsletter .bwh-topic-content ul, .bwh-newsletter .bwh-topic-content ol { margin: 0 0 {{ para }}px 0; padding-left: 22px; }
  .bwh-newsletter .bwh-topic-content li { margin-bottom: 6px; line-height: {{ lh }}; }
  .bwh-newsletter .bwh-topic-content h1, .bwh-newsletter .bwh-topic-content h2, .bwh-newsletter .bwh-topic-content h3 { font-family: {{ font_heading }}; line-height: 1.3; margin: {{ para + 6 }}px 0 {{ para }}px 0; }
  .bwh-newsletter .bwh-topic-content blockquote { margin: 0 0 {{ para }}px 0; padding: 4px 0 4px 16px; border-left: 3px solid {{ accent }}; color: {{ hex_to_rgba(page_fg, 0.8) }}; }

  /* ---- Contributors (byline) ---- */
  .bwh-contributors { margin-bottom: 14px; font-size: 0; }
  .bwh-contributor { display: inline-block; vertical-align: middle; margin: 0 20px 8px 0; font-size: 12px; }
  .bwh-avatar, .bwh-contributor-text { display: inline-block; vertical-align: middle; }
  .bwh-avatar { width: 28px; height: 28px; line-height: 28px; text-align: center; border-radius: 50%; font-family: {{ font_label }}; font-size: 11px; font-weight: 700; margin-right: 9px; }
  .bwh-contributor-text { font-family: {{ font_body }}; font-size: 12px; line-height: 1.35; }
  .bwh-contributor-text .bwh-name { font-weight: 600; }
  .bwh-contributor-text .bwh-role { display: block; font-family: {{ font_label }}; color: {{ muted }}; text-transform: uppercase; font-size: 9.5px; letter-spacing: 0.05em; margin-top: 1px; }

  /* ---- Media ---- */
  .bwh-media-grid { margin-bottom: 14px; font-size: 0; }
  .bwh-media-item { display: inline-block; vertical-align: top; text-align: left; margin: 0 12px 12px 0; font-size: {{ body_size }}px; }
  .bwh-media-item img, .bwh-media-item video { max-width: 100%; max-height: 340px; border-radius: {{ radius }}px; display: block; }
  .bwh-media-item .bwh-caption { font-family: {{ font_body }}; font-size: 11px; font-style: italic; color: {{ muted }}; margin-top: 6px; }

  /* ---- Links ---- */
  .bwh-links { font-family: {{ font_label }}; font-size: 12px; letter-spacing: 0.02em; line-height: 2; }
  .bwh-links a { color: inherit; text-decoration: none; margin-right: 18px; font-weight: 600; }
  .bwh-links a::after { content: " \2192"; }

  .bwh-footer { text-align: center; padding-top: 30px; padding-bottom: 34px; margin-top: 6px; font-family: {{ font_label }}; font-size: 10.5px; letter-spacing: 0.06em; text-transform: uppercase; color: {{ muted }}; border-top: 1px solid {{ divider }}; }

  .bwh-watermark { position: fixed; top: 50%; left: 50%; width: 55%; transform: translate(-50%, -50%) rotate(-25deg); z-index: 0; pointer-events: none; }
  @media print { .bwh-section { page-break-inside: avoid; } }
</style>

{% if S and S.custom_css %}<style>{{ S.custom_css }}</style>{% endif %}

{% if S and S.watermark_image %}
<img class="bwh-watermark" src="{{ file_url(S.watermark_image) }}" style="opacity: {{ ((S.watermark_opacity or 10) | int) / 100 }};" />
{% endif %}

{% if S and S.header_banner_image %}
<img class="bwh-banner" src="{{ file_url(S.header_banner_image) }}" />
{% endif %}

<div class="bwh-masthead" style="position: relative; z-index: 1;">
  <span class="bwh-wordmark">BWH Technologies</span>
  {% if doc.cover_image %}
  <img class="bwh-cover-img" src="{{ file_url(doc.cover_image) }}" />
  {% endif %}
  <h1>{{ doc.issue_title }}</h1>
  <div class="bwh-meta">
    {% if doc.publish_date %}{{ frappe.format_date(doc.publish_date) }}{% endif %}{% if doc.status %} &nbsp;&bull;&nbsp; {{ doc.status }}{% endif %}
  </div>
  <hr class="bwh-rule" />
</div>

{% if doc.description %}
<div class="bwh-intro" style="position: relative; z-index: 1;">{{ doc.description | safe }}</div>
{% endif %}

{#- Layout comes from the issue's own Sections and Topics tables (row order = print
    order). Work out what actually prints first: a topic with no content in this
    issue is skipped, and a section left with no printable topics is skipped too,
    so the contents list only names what appears. -#}
{% set printable = [] %}
{% for row in doc.sections or [] %}
  {% set blocks = [] %}
  {% for tr in doc.topics or [] if tr.section == row.section %}
    {% set contents = frappe.get_all("Newsletter Content", filters={"newsletter_issue": doc.name, "topic": tr.topic}, fields=["name", "title"], order_by="sort_order asc, title asc") %}
    {% if contents %}{% set _ = blocks.append({"topic": tr.topic, "contents": contents}) %}{% endif %}
  {% endfor %}
  {% if blocks %}{% set _ = printable.append({"row": row, "blocks": blocks}) %}{% endif %}
{% endfor %}

{% if printable %}
<div class="bwh-toc" style="position: relative; z-index: 1;">
  {% for p in printable %}<a href="#bwh-sec-{{ loop.index }}">{{ p.row.section }}</a>{% endfor %}
</div>
{% endif %}

{% for p in printable %}
  {%- set row = p.row -%}
  {%- set section = frappe.get_doc("Newsletter Section", row.section) -%}
  {%- set style_name = row.style or section.style -%}
  {%- set SS = frappe.get_doc("Newsletter Style", style_name) if style_name else None -%}
  {%- if SS and SS.custom_css %}<style>{{ SS.custom_css }}</style>{% endif -%}
  {%- set sec_accent = (SS.accent_color if SS and SS.accent_color else (SS.border_color if SS and SS.border_color else (palette[loop.index0 % (palette | length)] if palette else accent))) -%}
  {%- set is_panel = row.highlight or (SS is not none) -%}
  {%- set sec_panel_bg = (SS.background_color if SS and SS.background_color else (panel_bg if panel_bg else hex_to_rgba(sec_accent, 0.08))) -%}
  {%- set sec_fg = (SS.text_color if SS and SS.text_color else page_fg) -%}
  {%- if divider_style == 'Double' %}{% set sec_divider = '4px double ' ~ divider %}
  {%- elif divider_style == 'Thick' %}{% set sec_divider = '3px solid ' ~ sec_accent %}
  {%- elif divider_style == 'Dotted' %}{% set sec_divider = '2px dotted ' ~ divider %}
  {%- elif divider_style == 'None' %}{% set sec_divider = 'none' %}
  {%- else %}{% set sec_divider = '1px solid ' ~ divider %}{% endif -%}

  <div id="bwh-sec-{{ loop.index }}"
       class="bwh-section {{ 'bwh-section-panel' if is_panel else 'bwh-section-plain' }}"
       style="position: relative; z-index: 1; color: {{ sec_fg }};
              {% if is_panel %}background-color: {{ sec_panel_bg }};{% else %}border-top: {{ sec_divider }};{% endif %}">
    <div class="bwh-eyebrow">
      {% if show_numbers %}<span class="bwh-index">{{ "%02d"|format(loop.index) }}</span>{% endif %}
      <span class="bwh-dot" style="background: {{ sec_accent }};"></span>
      <h2 class="bwh-section-title"{% if accent_headings %} style="color: {{ sec_accent }};"{% endif %}>{{ section.section_name }}</h2>
    </div>

    <div class="bwh-topics-list">
    {% for block in p.blocks %}
      <div class="bwh-topic">
        <div class="bwh-topic-title">{{ block.topic }}</div>

        {% for c in block.contents %}
        {%- set content = frappe.get_doc("Newsletter Content", c.name) -%}
        {%- set TS = frappe.get_doc("Newsletter Style", content.style) if content.style else None -%}
        {%- if TS and TS.custom_css %}<style>{{ TS.custom_css }}</style>{% endif -%}
        <div class="bwh-content"{% if TS %} style="padding: 14px 16px; border-radius: {{ radius }}px;{% if TS.background_color %} background-color: {{ TS.background_color }};{% endif %}{% if TS.text_color %} color: {{ TS.text_color }};{% endif %}"{% endif %}>
          {#- One piece with the same title as its topic: the topic heading is enough. -#}
          {% if (block.contents | length) > 1 or ((content.title or '') | trim | lower) != (block.topic | trim | lower) %}
          <div class="bwh-content-title">{{ content.title }}</div>
          {% endif %}

          {% if content.contributors %}
          <div class="bwh-contributors">
            {% for cb in content.contributors %}
            <div class="bwh-contributor">
              <span class="bwh-avatar" style="background: {{ hex_to_rgba(sec_accent, 0.16) }}; color: {{ sec_accent }};">{{ (cb.employee_name or "?")[0] }}</span>
              <span class="bwh-contributor-text">
                <span class="bwh-name">{{ cb.employee_name }}</span>
                <span class="bwh-role">{{ cb.designation or "" }}{% if cb.contribution_role %} &middot; {{ cb.contribution_role }}{% endif %}</span>
              </span>
            </div>
            {% endfor %}
          </div>
          {% endif %}

          {% if content.body %}
          <div class="bwh-topic-content">{{ content.body | safe }}</div>
          {% endif %}

          {% if content.media %}
          <div class="bwh-media-grid">
            {% for m in content.media %}
              {% set m_url = file_url(m.attachment) %}
              <div class="bwh-media-item">
                {% if m.media_type == "Video" %}
                  <video controls src="{{ m_url }}"></video>
                {% else %}
                  <img src="{{ m_url }}" />
                {% endif %}
                {% if m.caption %}<div class="bwh-caption">{{ m.caption }}</div>{% endif %}
              </div>
            {% endfor %}
          </div>
          {% endif %}

          {% if content.reference_links %}
          <div class="bwh-links" style="color: {{ sec_accent }};">
            {% for l in content.reference_links %}<a href="{{ l.url }}" target="_blank">{{ l.label }}</a>{% endfor %}
          </div>
          {% endif %}
        </div>
        {% endfor %}
      </div>
    {% endfor %}
    </div>
  </div>
{% endfor %}

<div class="bwh-footer" style="position: relative; z-index: 1;">
  Published by BWH Technologies LLP &nbsp;&bull;&nbsp; Built on Frappe
</div>

</div>
"""


def _render_html():
	_write_fonts_css()
	return HTML


def create_print_format():
	if frappe.db.exists("Print Format", PRINT_FORMAT_NAME):
		pf = frappe.get_doc("Print Format", PRINT_FORMAT_NAME)
	else:
		pf = frappe.new_doc("Print Format")
		pf.name = PRINT_FORMAT_NAME
		pf.doc_type = "Newsletter Issue"
		pf.module = "Newsletter"

	pf.custom_format = 1
	pf.print_format_type = "Jinja"
	pf.standard = "No"
	pf.disabled = 0
	pf.html = _render_html()
	pf.page_size = "A4"
	pf.margin_top = 0
	pf.margin_bottom = 0
	pf.margin_left = 0
	pf.margin_right = 0
	pf.align_labels_right = 0
	pf.show_section_headings = 0
	pf.line_breaks = 0
	pf.font_size = 12
	pf.default_print_language = "en"

	if pf.is_new():
		pf.insert(ignore_permissions=True)
	else:
		pf.save(ignore_permissions=True)

	# Make it the default print format for Newsletter Issue.
	filters = {"doc_type": "Newsletter Issue", "property": "default_print_format"}
	if frappe.db.exists("Property Setter", filters):
		ps = frappe.get_doc("Property Setter", filters)
	else:
		ps = frappe.new_doc("Property Setter")
	ps.doctype_or_field = "DocType"
	ps.doc_type = "Newsletter Issue"
	ps.property = "default_print_format"
	ps.property_type = "Data"
	ps.value = pf.name
	ps.save(ignore_permissions=True)

	frappe.db.commit()
	print(f"Print Format ready: {pf.name}")


if __name__ == "__main__":
	create_print_format()
